### ISSUE TITLE
Unicode support (UTF-8)

### ISSUE THREAD

**Issue by nullJaX** [nullJaX/Maltego-Google-Transforms#1]
Transforms return errors caused by:

`AppData\Local\Programs\Python\Python35\lib\encodings\cp1250.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 8: character maps to <undefined>`

**Comment by glerinsonum** [comment]
@nullJaX Hi Bro. Do you have time to talks together, at facebook. about Maltego iTDDS Server

**Comment by nullJaX** [comment]
@glerinosum, this project is no longer developed due to constant changes both in Maltego and Google+. In addition, the communication with Google+ API was not always perfect and the social platform itself  provides not-so-much user information from the OSINT point of view. However, if you want to use this code somewhere else or improve it, feel free to do so.

**Comment by rough-enough** [comment]
?
